// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShbMY4x8NaCyBO-fkFx2_J5WrhABvUf4',
    appId: '1:191253187352:web:0ae9b59bcdfa45749d2c6d',
    messagingSenderId: '191253187352',
    projectId: 'fireauth-6f9d4',
    authDomain: 'fireauth-6f9d4.firebaseapp.com',
    storageBucket: 'fireauth-6f9d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFlMqcAT1NezBogBXSLMzXunkDYlsjWlA',
    appId: '1:191253187352:android:b7d8acb1c0284fe19d2c6d',
    messagingSenderId: '191253187352',
    projectId: 'fireauth-6f9d4',
    storageBucket: 'fireauth-6f9d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYXhTGmxSmr59hp0HuvKrHsUEMpXmjJaI',
    appId: '1:191253187352:ios:6280fd1b4ed97a119d2c6d',
    messagingSenderId: '191253187352',
    projectId: 'fireauth-6f9d4',
    storageBucket: 'fireauth-6f9d4.appspot.com',
    iosClientId: '191253187352-8adast5r0itcse8sl6ki94dfd7rq2pcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYXhTGmxSmr59hp0HuvKrHsUEMpXmjJaI',
    appId: '1:191253187352:ios:6280fd1b4ed97a119d2c6d',
    messagingSenderId: '191253187352',
    projectId: 'fireauth-6f9d4',
    storageBucket: 'fireauth-6f9d4.appspot.com',
    iosClientId: '191253187352-8adast5r0itcse8sl6ki94dfd7rq2pcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireauth',
  );
}
